[workspace]
authors = ["Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>"]
channels = ["conda-forge", "bioconda"]
name = "eval-samtools-cpu-efficiency"
platforms = ["linux-64","osx-arm64"]
version = "0.1.0"

[tasks]
test = "nextflow run main.nf -profile hpc"
clean-work = "nextflow clean -f -before $(nextflow log -q | tail -n 1)"

[dependencies]
nextflow = ">=25.4.3,<26"
nf-core = ">=3.3.1,<4"
