[workspace]
authors = ["Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>"]
channels = ["conda-forge", "bioconda"]
name = "eval-samtools-cpu-efficiency"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
nextflow = ">=25.4.3,<26"
nf-core = ">=3.3.1,<4"
